name: Heroku Auto Start/Stop

on:
  schedule:
    - cron: '*/5 * * * *'   # testing every 5 mins
  workflow_dispatch:

jobs:
  control:
    runs-on: ubuntu-latest

    steps:
      - name: Start/Stop Dyno via API
        run: |
          MIN=$(date -u +"%M")

          if [ "$MIN" -lt 30 ]; then
            echo "STARTING APP"
            curl -n -X PATCH https://api.heroku.com/apps/japaneselanguagejobs/formation \
              -H "Accept: application/vnd.heroku+json; version=3" \
              -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
              -H "Content-Type: application/json" \
              -d '{"updates":[{"type":"web","quantity":1}]}'
          else
            echo "STOPPING APP"
            curl -n -X PATCH https://api.heroku.com/apps/japaneselanguagejobs/formation \
              -H "Accept: application/vnd.heroku+json; version=3" \
              -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
              -H "Content-Type: application/json" \
              -d '{"updates":[{"type":"web","quantity":0}]}'
          fi
